### PR TITLE
The lifting of a set is a set

### PR DESCRIPTION
**Pull request by tomdjong**
Also proved that the product of two sets is a set (see UF-Subsingletons).

### CODE REVIEW

**Comment by martinescardo** [comment]
Thanks. Another proof is possible using that `is-prop (l ⊑ m)` for the lifting of a set, proved in LiftingUnivalentPrecategory, and that `⊑` is antiysymmetric, so that we get a constat map `l = m -> l = m` and we can apply Hedberg to get that the lifting is a set. But your proof is also short enough.

**Comment by martinescardo** [comment]
Please import your file at PartialElements.lagda so that `agda AllModulesIndex.lagda` processes it.

**Comment by tomdjong** [comment]
Cool, I like that.

New pull request coming up.

**Comment by martinescardo** [comment]
We should eventually set up an automatic script to compile everything when something is added...

**Comment by martinescardo** [comment]
Please observe the convention of writing e.g. "(X : 𝓤  ̇ )" with a space between the dot and the bracket. This is needed to make the automatically generated html readable.

**Comment by tomdjong** [comment]
Apologies, fixed in new pull request.

**Comment by martinescardo** [comment]
No need to apologize. I need to write a file with convention guidelines.

**Pull request merged**
