### PR TITLE
Add a definition of frames

### PR DESCRIPTION
**Pull request by ayberkt**
I have used combinators for Ω in this development that I defined inside the `Frame` module. Instead of adding such ad-hoc definitions, we should first address #43 in a separate PR in my opinion.

### CODE REVIEW

**Comment by ayberkt** [comment]
@martinescardo

Changes we discussed yesterday have now been incorporated and this PR is ready for review.

Removing the explicit h-set requirement has the consequence that my function

```agda
satisfies-frame-laws : {A : 𝓤 ̇} → frame-data 𝓥 𝓦 A → 𝓤 ⊔ 𝓥 ⊔ 𝓦 ⁺ ̇
```

is no longer a proposition. Isn't this problematic? I recall needing this in [`formal-topology-in-UF`](https://github.com/ayberkt/formal-topology-in-UF/).

**Comment by martinescardo** [comment]
This should still be a proposition.

**Comment by martinescardo** [comment]
Nice. Please add: (1) the initial date of creation of the file next to your name at the top of each file, (2) an import entry in theindex file index.lagda (with your name in the imports like the other ones). And (3), make sure "agda AllmodulesIndex.lagda" succeeds. At the moment  I don't have this set up for git to check (but you are welcome to add this feature if you want). Thanks.

**Comment by ayberkt** [comment]
I have made the changes (1), (2), and (3).

> This should still be a proposition.

Antisymmetry is now a structure and not a proposition. It used to be grouped together with the other laws but now that it is not propositional, I would have to group it with the structures to maintain a clean separation of the structure and data involved in defining a frame. Is this what you meant? Otherwise, I don't see how `is-partial` would be propositional. If I already know that a type is equipped with a reflexive and antisymmetric relation, I know that the antisymmetry of the relation is propositional, but this doesn't help me at the point when I'm asserting the antisymmetry.

**Comment by martinescardo** [comment]
> I have made the changes (1), (2), and (3).
> 
> > This should still be a proposition.
> 
> Antisymmetry is now a structure and not a proposition. It used to be grouped together with the other laws but now that it is not propositional, I would have to group it with the structures to maintain a clean separation of the structure and data involved in defining a frame. Is this what you meant? Otherwise, I don't see how `is-partial` would be propositional. If I already know that a type is equipped with a reflexive and antisymmetric relation, I know that the antisymmetry of the relation is propositional, but this doesn't help me at the point when I'm asserting the antisymmetry.

Whether a frame is assumed to be a set, or proved to be a set (from antisymmetry) should *not* make a difference. In the treatment of ordinals, I also don't assume that the underlying types are sets (because this follows from the extensionality condition), but I often do need to know that it is a set in order to prove that certain things are propositions. The same should be the case for you.

**Pull request merged**
