### PR TITLE
Formalizing Christensen's result on small types and connectedness

### PR DESCRIPTION
**Pull request by IanRay11**
I am starting a draft for the Dan Christensen paper.

### CODE REVIEW

**Comment by martinescardo** [comment]
Are you planning to continue with this work?

**Comment by IanRay11** [comment]
Now that summer has begun I do plan to get back to some of my work in TypeTopology. Including this

**Comment by ayberkt** [comment]
@IanRay11 What is the status of this PR? Is it possible that it has been subsumed by any of the recently merged PRs? Should we close it if there is no plan to work on it any longer?

**Comment by IanRay11** [comment]
No do not close it. Now that I have all the preliminary concepts in place I can continue it.

**Comment by ayberkt** [comment]
@IanRay11 Great, thanks for the update!

**Pull request closed without merging**
