### PR TITLE
Scott model of PCF

### PR DESCRIPTION
**Pull request by tomdjong**
Includes:
- the lifting of a set is a dcpo with bottom;
- construction of the dcpo of continuous functions;
- the interpretation of PCF types as dcpos with bottom;
- the interpretation of PCF terms as elements of these dcpos with bottom.

### CODE REVIEW

**Comment by martinescardo** [comment]
It also includes the fixed point theorem for continuous functions.

**Comment by martinescardo** [comment]
I will change some notation to adhere to conventions in use in this development.

**Comment by tomdjong** [comment]
> I will change some notation to adhere to conventions in use in this development.

Okay, I will keep an eye on the changes for future reference.

**Comment by martinescardo** [comment]
#0f6ba5b8075f493f08d2570885d94210a644ac51

**Comment by martinescardo** [comment]
Done.

**Pull request merged**
