### PR TITLE
Unused imports

### PR DESCRIPTION
**Pull request by tomdjong**
@martinescardo I will continue cleaning in this PR. Please leave it open for now.

### CODE REVIEW

**Comment by ayberkt** [comment]
It might also be a good idea to include this script in the CI checks. We can avoid the addition of new modules with unused imports this way.

**Comment by tomdjong** [comment]
@ayberkt We should only run it on new (or maybe modified) files then because this has the potential of being very slow.

**Comment by martinescardo** [comment]
> @ayberkt We should only run it on new (or maybe modified) files then because this has the potential of being very slow.

Agreed!

**Comment by ayberkt** [comment]
> We should only run it on new (or maybe modified) files then

That is a good point. Running it only on modified files should be possible.

How does the script detect unused imports?

**Comment by tomdjong** [comment]
By uncommenting line by line and seeing if it compiles. The script file should be readable and essentially self-explanatory.

**Pull request merged**
