### PR TITLE
A few lemmas for the formalizations of connections between small and connected types

### PR DESCRIPTION
**Pull request by IanRay11**
I was having a github issue so I am just pushing my current progress

### CODE REVIEW

**Comment by IanRay11** [comment]
@tomdjong I have recently experienced a huge slow down since I added all my computations rules. Any ideas why this is happening?

**Comment by tomdjong** [comment]
@IanRay11 Let's discuss this in the thread on Discord instead. For now, let me suggest that you try to isolate the issue by (un)commenting parts of the code and experimenting.

**Comment by tomdjong** [comment]
@IanRay11 and I agreed that this will PR will be split in three smaller PRs to facilitate reviewing.

**Comment by IanRay11** [comment]
I think this can be closed now right? @tomdjong

**Pull request closed without merging**
