### PR TITLE
[WIP] Continuing with duploids

### PR DESCRIPTION
**Pull request by jonsterling**
Just a work-in-progress branch cleaning up my duploid development, and getting ready to prove more results. Will post an update when it's ready for review, but happy to have any suggestions or critique along the way. 

- Imposes an appropriately polarized version of the univalence condition
- Replaces the definition of duploids with one in which all structure beyond the underlying deductive system is mere property: this includes polarized univalence, polarization, and the presence of shifts. The latter are only property by virtue of polarized univalence.
- From a duploid, defines the four categories (positives and negatives with effectful or pure maps), and the adjunction between positives and negatives with effectful maps

### CODE REVIEW

**Comment by jonsterling** [comment]
@martinescardo I seem to recall at one point you suggested renaming `Duploid.agda` to `Type.agda` or something along these lines. Do I remember this correctly? Or were there other changes to the organization of these files that you felt would improve it?

**Comment by martinescardo** [comment]
> @martinescardo I seem to recall at one point you suggested renaming `Duploid.agda` to `Type.agda` or something along these lines. Do I remember this correctly? Or were there other changes to the organization of these files that you felt would improve it?

Yes, I suggested this modification. For some reason I didn't see the notification for your message of a few days ago.

**Comment by martinescardo** [comment]
Any progress with this?

**Comment by martinescardo** [comment]
Is there an intention to continue this work?

**Comment by jonsterling** [comment]
Hi @martinescardo, I apologise, but I ran out of time and do not expect to continue this PR.

**Pull request closed without merging**
