### PR TITLE
Semidecidablity: constructive taboos, choice principles and closure properties.

### PR DESCRIPTION
**Pull request by tomdjong**
Please see the top of the file `SemiDecidable.lagda` for an overview of the contents of this PR.

Added some (small) general lemmas in eight other files.

### CODE REVIEW

**Review by martinescardo — CHANGES_REQUESTED** [review]
Some minimal changes as discussed verbally.

**Comment by tomdjong** [comment]
Requested changes made. Could you let me know when the HTML rendering is live please?

**Review by martinescardo — APPROVED** [review]
Wonderful.

**Comment by martinescardo** [comment]
Thanks for the contribution!

**Comment by martinescardo** [comment]
> Requested changes made. Could you let me know when the HTML rendering is live please?

It is is live now.

**Pull request merged**
