### PR TITLE
Banach fixed-point theorem

### PR DESCRIPTION
**Pull request by tnttodda**
The Banach fixed-point theorem for co-ultrametric types

### CODE REVIEW

**Review by martinescardo — CHANGES_REQUESTED** [review]
I think you didn't mean to commit this file.

**Comment by tnttodda** [comment]
I'll make a new request -- can't figure out a clean way to do it

**Comment by tnttodda** [comment]
Okay, I've reverted the commit! You can safely pull now

**Comment by martinescardo** [comment]
Thanks.

**Pull request merged**
